[package]
name = "lyra-preprocess"
edition.workspace = true
license.workspace = true
version.workspace = true

[lints]
workspace = true

[dependencies]
lyra-source.workspace = true
lyra-lexer.workspace = true
smol_str.workspace = true
