[package]
name = "lyra-parser"
edition.workspace = true
license.workspace = true
version.workspace = true

[lints]
workspace = true

[dependencies]
lyra-source.workspace = true
lyra-lexer.workspace = true
lyra-diag.workspace = true
rowan.workspace = true
